### ISSUE TITLE
#19 세션 vs JWT

### ISSUE THREAD

**Issue by LeeJongbokz** [LeeJongbokz/interviewPrep#51]
세션 vs JWT
https://velog.io/@gotaek/%EC%84%B8%EC%85%98Session%EA%B3%BC-JWT

**Comment by Jineh** [comment]
[session, jwt 장단점]
https://studyandwrite.tistory.com/499

**Comment by LeeJongbokz** [comment]
JWT를 선택했음
- Refresh 토큰도 적용할 예정임
